# ── Base de données ────────────────────────────────────────────────
connection.dialect      = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url          = jdbc:postgresql://postgres:5432/dhis2
connection.username     = postgres
connection.password = SanteSecure2024!
connection.pool.max_size = 10
# ── URL publique — CRITIQUE pour les redirections après login ──────


server.base.url = https://vps-27978dbd.vps.ovh.net/dhis2

# ── Sécurité ───────────────────────────────────────────────────────
encrypt.password  = on
keycloak.enabled  = off
